apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lfgp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0044-tenant/tkrw-pr712-0075-0044-app/devfile-sample-lfgp@sha256:01f254f8fa2b68c72425b6521b777774c038e599d3252b0c1dc27d21651a3e41
        name: my-nodejs
        resources: {}
status: {}
